### ISSUE TITLE
Isuue with copy functionality

### ISSUE THREAD

**Issue by akshayreddy** [justcaliturner/simple-code-editor#15]
## Description

The copy code functionality stopped working. 
Basically,  what happens is, the previous information copied stays forever, no matter the changes to the binded `value` attribute. Also, the copy feature does not work if something else is already copied.

I investigated and found that it might be an issue caused due to a recent `Chrome` update because the functionality was working perfectly on the previous versions and interestingly it works fine on `Firefox` browser.

##### import the `simple-code-editor` by adding the dependency

```vue
<template>
  <span>static value</span>
  <code-editor value="console.log(10)"></code-editor>
  <br />
  <span>value keeps changing</span>
  <code-editor :value="somevalue"></code-editor>
</template>

<script>
import CodeEditor from "simple-code-editor";

export default {
  name: "App",
  components: {
    CodeEditor: CodeEditor,
  },
  data() {
    return {
      somevalue: "console.log(1)",
    };
  },

  mounted() {
    setInterval(this.changevalue, 10000);
  },

  methods: {
    changevalue() {
      this.somevalue = `console.log(${Math.random()})`;
    },
  },
};
</script>
```

## versions

- simple-code-editor: `1.2.0`
- chrome: `101.0.4951.54 (Official Build) (x86_64)`
- firefox: `100.0 (64-bit)`

**Comment by justcaliturner** [comment]
@akshayreddy  Thanks for the feedback, I found this error was just thrown in the CodeSandbox,  and the reason is maybe for the browser permissions about the `clipboard` API in the CodeSandbox. But anyway, I have put the `clipboard` API behind the `execCommand` API, and it will use the old way to copy the content first, you can update the npm package to 1.2.2 and try it, and this is the demo in the CodeSandbox: https://codesandbox.io/s/confident-clarke-8h5u1s?file=/src/components/HelloWorld.vue:600-609

**Comment by akshayreddy** [comment]
@justcaliturner I have made the update and looks like it is working pretty well. Thank you for the fix. 👍
